// Generated by CoffeeScript 1.4.0

/*
doT Express Master of Ceremonies
@author Dannel Albert <cuebix@gmail.com>
*/


(function() {
  var cache, curOptions, curPath, def, defaults, doT, fs, html, mergeObjects, path, renderFile, workingPaths;

  fs = require("fs");

  path = require("path");

  doT = require("dot");

  try {
    html = require("html");
  } catch (e) {
    if (e.code !== "MODULE_NOT_FOUND") {
      throw e;
    }
  }

  cache = {};

  workingPaths = [];

  curOptions = null;

  curPath = null;

  defaults = {
    fileExtension: "def",
    options: {
      templateSettings: {
        cache: true
      }
    }
  };

  if (html) {
    defaults.options.prettyPrint = {
      indent_char: "	",
      indent_size: 1
    };
  }

  def = {
    "include": function(filename) {
      var returnValue, template;
      returnValue = void 0;
      if (!path.extname(filename)) {
        filename = "" + filename + "." + defaults.fileExtension;
      }
      if (curPath) {
        filename = path.resolve(curPath, filename);
      }
      curPath = path.dirname(filename);
      workingPaths.push(curPath);
      try {
        if (curOptions.templateSettings.cache && filename in cache) {
          template = cache[filename];
        } else {
          template = cache[filename] = fs.readFileSync(filename, 'utf8');
        }
        returnValue = doT.template(template, curOptions.templateSettings, def)(curOptions);
      } catch (err) {
        workingPaths.pop();
        curPath = workingPaths.length ? workingPaths[workingPaths.length - 1] : null;
        throw err;
      }
      curPath = workingPaths.length ? workingPaths[workingPaths.length - 1] : null;
      return returnValue;
    }
  };

  mergeObjects = function(target) {
    var arg, argLength, deep, i, key;
    if (typeof target !== "object") {
      if (arguments.length === 1) {
        return target;
      }
      deep = (target ? true : false);
      target = arguments[1];
      i = 2;
    } else {
      deep = false;
      i = 1;
    }
    argLength = arguments.length;
    if (deep) {
      while (i < argLength) {
        arg = arguments[i];
        for (key in arg) {
          if (typeof arg === "object" && typeof target[key] === "object") {
            target[key] = mergeObjects(deep, target[key], arg[key]);
          } else {
            target[key] = arg[key];
          }
        }
        i++;
      }
    } else {
      while (i < argLength) {
        arg = arguments[i];
        for (key in arg) {
          target[key] = arg[key];
        }
        i++;
      }
    }
    return target;
  };

  renderFile = function(filename, options, fn) {
    if (typeof options === "function") {
      fn = options;
      options = {};
    }
    if (typeof fn !== "function") {
      fn = (function() {});
    }
    curOptions = mergeObjects(true, options, defaults.options, {
      templateSettings: doT.templateSettings
    });
    try {
      if (html && curOptions.pretty) {
        return fn(null, html.prettyPrint(def.include(filename), curOptions.prettyPrint || {}));
      } else {
        return fn(null, def.include(filename));
      }
    } catch (err) {
      return fn(err);
    }
  };

  exports.__express = renderFile;

  exports.renderFile = renderFile;

  exports.init = function(settings) {
    defaults = mergeObjects(true, defaults, settings);
    return exports;
  };

}).call(this);
